<a href="https://colab.research.google.com/github/Sneha-Srivastava/Python_Course/blob/main/Practice_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Assignment

In [3]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a.shape

(3, 4)

In [5]:
a.ndim 

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size 

12

In [9]:
type(a)

numpy.ndarray

Array creation

In [11]:
a = np.array([12, 33, 24])
a 

array([12, 33, 24])

In [14]:
b = np.array([1.3, 4.5, 8.1])
b

array([1.3, 4.5, 8.1])

In [20]:
c = np.array([[11, 22] , [33, 44]] , dtype = complex)
c

array([[11.+0.j, 22.+0.j],
       [33.+0.j, 44.+0.j]])

In [21]:
np.zeros((1,3)) 

array([[0., 0., 0.]])

In [22]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
np.empty((2,3))

array([[4.66815576e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [25]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [28]:
from numpy import pi
np.linspace(0, 2, 9)
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


Basic Operations

In [32]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
c = a-b 
c

array([10, 19, 28, 37])

Matrix Multiplication

In [33]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
A * B    
A @ B     
A.dot(B)

array([[5, 4],
       [3, 4]])

In [39]:
rg = np.random.default_rng(1) 
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

Universal Functions

In [49]:
B = np.arange(3)
B
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C) 
#Indexing and slicing 
a = np.arange(10)**3 
a[2]
a[2 : 5] 
a[ : 6 : 2] = 1000